Include `killed` boolean in command result
kimmobrunfeldt/concurrently pull request #250
Opened 2020-11-23 17:08 UTC by Roaders

The exit code of each command is already included in the result but the usefulness of this is limited if concurrently is run with `killOthers`. When parsing the result you do not know if a non-0 exit code is because the command failed or if it was killed by concurrently.

Adding this option allows you to print a message at the end identifying exactly which commands caused the initial failure.

2021-02-23 09:13 UTC, Roaders commented
Any chance we can get this PR considered?

2021-05-09 02:01 UTC, gustavohenke requested changes
Hey! Can we also get some test for this, please?

2021-05-09 07:37 UTC, Roaders commented
I was going to write tests but tests were failing before I started so it's hard to know where to start.

2021-05-09 07:48 UTC, Roaders commented
As far as I can tell there are no existing tests that test the exit condition of multiple commands in the `close` stream. I am trying to find one to base my tests on.

2021-05-09 08:31 UTC, Roaders commented
OK, I figured it out. Been so long since I did this I had forgotten the structure of the project.

2021-05-09 10:55 UTC, gustavohenke approved these changes
Thanks for the side fixes!

2021-05-09 10:55 UTC, gustavohenke commented on src/command.spec.js
> +    it('should mark the command as killed', done => {
```suggestion
    it('marks the command as killed', done => {
```

2021-05-09 11:05 UTC, Roaders commented
Do I have to do anything to merge this? I assume you'll merge it at some point.
Thanks.

2021-05-09 12:47 UTC, merged

2021-05-24 10:27 UTC, Roaders commented
Any idea when this will be released?

2021-05-24 10:45 UTC, gustavohenke commented
Heya. Just released it in v6.2.0.

2021-05-24 10:48 UTC, Roaders commented
brilliant, thanks